---
title : "ITCR-bioconductor"
---

This site automatically tracks GitHub repositories associated with NCI grant [1U24CA289073-01](https://reporter.nih.gov/project-details/10865962) to the CUNY Graduate School of Public Health and Health Policy.* PI: [Levi Waldron](https://scholar.google.com/citations?user=-Bfm-2IAAAAJ&hl=en&oi=ao) * co-Investigators: [Sean Davis](https://scholar.google.com/citations?user=hLFc29kAAAAJ&hl=en&oi=ao)

## Navigation

* **[Overview](./overview.html)**: Project abstract.

* **[Projects](./projects.html)**: A table of all repositories found for the tracked topic.

* **[Recent Commits](./commit_log.html)**: A blog-style feed of the latest commits from all listed projects.

## Public Health Relevance

Cancer research increasingly relies on multimodal data integration—encompassing genomic, transcriptomic, and imaging data—to unravel the complexities of tumor biology and the tumor microenvironment (TME). Histopathological examination of hematoxylin and eosin (H&E)-stained slides remains central to cancer diagnosis and prognostication. The digitization of these slides into high-resolution whole slide images (WSIs) has unlocked opportunities to extract spatially-resolved features using advanced computational tools. While R/Bioconductor dominates omics research due to its robust statistical capabilities, image analysis remains primarily Python-based, creating barriers to seamless integration. This proposal aims to bridge this gap by developing interoperable workflows and tools that connect Python-based image analysis outputs with R/Bioconductor, enabling comprehensive multimodal analyses within a unified ecosystem.
